SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS report_weaknesses;
DROP TABLE IF EXISTS reports;
DROP TABLE IF EXISTS mastery_records;
DROP TABLE IF EXISTS question_attempts;
DROP TABLE IF EXISTS learning_events;
DROP TABLE IF EXISTS learning_sessions;
DROP TABLE IF EXISTS plan_overrides;
DROP TABLE IF EXISTS daily_plan_tasks;
DROP TABLE IF EXISTS daily_plans;
DROP TABLE IF EXISTS question_knowledge_nodes;
DROP TABLE IF EXISTS question_bank;
DROP TABLE IF EXISTS knowledge_relations;
DROP TABLE IF EXISTS knowledge_nodes;
DROP TABLE IF EXISTS content_packages;
DROP TABLE IF EXISTS parent_preferences;
DROP TABLE IF EXISTS child_profiles;
DROP TABLE IF EXISTS user_sessions;
DROP TABLE IF EXISTS user_credentials;
DROP TABLE IF EXISTS users;
SET FOREIGN_KEY_CHECKS = 1;
